# Generated by Django 4.1 on 2023-10-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthYay', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, related_name='following', to='birthYay.user'),
        ),
    ]
