# Generated by Django 4.1 on 2023-10-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthYay', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to='birthYay.user'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_given', to='birthYay.user'),
        ),
    ]
