# Generated by Django 4.1 on 2023-11-05 01:21

import birthYay.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthYay', '0004_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True, validators=[birthYay.validators.validate_date_in_past]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.DecimalField(blank=True, null=True, decimal_places=2, max_digits=10, validators=[birthYay.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='gift',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(editable=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='message',
            field=models.CharField(blank=True, default='Have a peek!', max_length=254),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
