# Generated by Django 4.1 on 2023-11-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthYay', '0005_alter_customuser_birthday_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
