# Generated by Django 4.1 on 2023-11-09 04:05

import birthYay.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birthYay', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='gift',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='birthYay.gift'),
        ),
    ]
